changelog:
  categories:
    - title: 💥 Breaking changes
      labels:
        - '💥 Breaking changes'
    - title: ✨ New features
      labels:
        - '✨ Feature'
    - title: 💫 Improvements
      labels:
        - '💫 Improvements'
        - '💄 UI/UX'
    - title: 🐛 Bug fixes
      labels:
        - '🐛 bug'
        - '🚑 Hotfix'
    - title: ⚡ Performances
      labels:
        - '⚡ Performances'
    - title: 🔒 Security
      labels:
        - '🔒 Security'
    - title: 📝 Documentation
      labels:
        - '📝 Documentation'
        - 'scope: docs'
        - '🌐 Translations'
    - title: ♻️ Refactoring
      labels:
        - '♻️ Refactoring'
    - title: ✅ Tests
      labels:
        - '✅ Tests'
    - title: 👷 CI
      labels:
        - '👷 CI'
        - github_actions
        - 'scope: deployment'
    - title: 🏗️ Maintenance
      labels:
        - dependencies
        - '🏗️ Maintenance'
    - title: Other Changes
      labels:
        - "*"
