[project]
dynamic = ["version"]
name = "osm-paths"
dependencies = [
    "Django",
    "djangorestframework",
    "osmnx",
    "gunicorn",
]
[project.optional-dependencies]
dev = [
    "tblib",
    "coverage",
    "ruff",
    "uv"
]