name: Linting

on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  flake8:
    name: Checking lint rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
            version: "latest"
            python-version: "3.12"
            enable-cache: true
            cache-suffix: "ruff"

      - name: Install dependencies
        run: |
          uv pip install ruff -c requirements-dev.txt

      - name: Check linting
        run: |
          ruff check osm-paths

      - name: Check format
        run: |
          ruff format --check osm-paths
