name: Release

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    release:
        if: ${{ github.event.workflow_run.conclusion == 'success' && ()github.ref == 'refs/heads/main' || github.event_name == 'release') }}
        runs-on: ubuntu-latest
        permissions:
            packages: write  # required to publish docker image
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v3

        - name: Extract metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images:  |
              ghcr.io/makinacorpus/osm-paths

        - name: Build and push image
          uses: docker/build-push-action@v6
          with:
              push: true
              provenance: mode=max
              sbom: true
              builder: ${{ steps.buildx.outputs.name }}
              tags: ${{ steps.meta.outputs.tags }}
