name: Testing

on:
  pull_request:
  push:
    branches: 
      - main
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Python Unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
            version: "latest"
            python-version: "3.12"
            enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install -r requirements-dev.txt

      - name: run Tests
        run: |
          coverage run --parallel-mode --concurrency=multiprocessing ./manage.py test --parallel -v 3
          coverage combine
          coverage xml -o coverage.xml

      - uses: codecov/codecov-action@v5
        with:
            files: ./coverage.xml
            #token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: true # optional (default = false)
